# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtunAT054 < Formula
  desc "atun.io is a simple SSM/SSH tunnel manager"
  homepage "https://github.com/AutomationD/atun"
  version "0.5.4"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AutomationD/atun/releases/download/v0.5.4/atun-darwin-amd64.tar.gz"
      sha256 "c37c592029ad1023a54665b94d31c8c0b5a8d2c93f17ed8924b7bb0f489c3430"

      def install
        bin.install "atun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AutomationD/atun/releases/download/v0.5.4/atun-darwin-arm64.tar.gz"
      sha256 "06dc822ebb3bc968717ce515c5bbd4c76a8f66d0cd6fda3db41ac52d46804c37"

      def install
        bin.install "atun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AutomationD/atun/releases/download/v0.5.4/atun-linux-amd64.tar.gz"
        sha256 "c9ed8ab87aa47ad9191be0a092f700834b73e17a27a5ba7ef7a1aa63a4f209a4"

        def install
          bin.install "atun"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AutomationD/atun/releases/download/v0.5.4/atun-linux-arm64.tar.gz"
        sha256 "a8c7024fbab0ca7106d77f5744eeb3f07be85bb4d29da4d6276150ab124afdc5"

        def install
          bin.install "atun"
        end
      end
    end
  end

  conflicts_with "atun-dev"
  conflicts_with "atun-dev@0.5.4"

  test do
    system "#{bin}/atun version"
  end
end
