# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtunAT080 < Formula
  desc "atun.io is a simple SSM/SSH tunnel manager"
  homepage "https://github.com/DimmKirr/atun"
  version "0.8.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DimmKirr/atun/releases/download/v0.8.0/atun-darwin-amd64.tar.gz"
      sha256 "4cd69474773f10f6f985b73022eb489deb45c02dda710fa3849bb19bcf593271"

      def install
        bin.install "atun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DimmKirr/atun/releases/download/v0.8.0/atun-darwin-arm64.tar.gz"
      sha256 "71ff0aa1917988e9adc3d1868d3d11be48360d8a7600d42106c0d2a46cf75291"

      def install
        bin.install "atun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/DimmKirr/atun/releases/download/v0.8.0/atun-linux-amd64.tar.gz"
      sha256 "78ea9e5475d5f6d2a0d2c656c3b02f6ec75d3cba8829752b6a7af3358c9c6719"
      def install
        bin.install "atun"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/DimmKirr/atun/releases/download/v0.8.0/atun-linux-arm64.tar.gz"
      sha256 "f47b2fa937ac6709aa7b9e833bc57c49b3154cb3196c1430cc1ae1c1b883d811"
      def install
        bin.install "atun"
      end
    end
  end

  conflicts_with "atun-dev"
  conflicts_with "atun-dev@0.8.0"

  test do
    system "#{bin}/atun version"
  end
end
