# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtunAT071 < Formula
  desc "atun.io is a simple SSM/SSH tunnel manager"
  homepage "https://github.com/AutomationD/atun"
  version "0.7.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AutomationD/atun/releases/download/v0.7.1/atun-darwin-amd64.tar.gz"
      sha256 "e09fe808b55c40b7466f8228e7db9f4ce3c66d35cd3682cc3d184b471f03591f"

      def install
        bin.install "atun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AutomationD/atun/releases/download/v0.7.1/atun-darwin-arm64.tar.gz"
      sha256 "45ff12e26e3608d007a76d0723d41bea8dec21a2c94df8ae927cd88a5295d89a"

      def install
        bin.install "atun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AutomationD/atun/releases/download/v0.7.1/atun-linux-amd64.tar.gz"
        sha256 "5a7a0d8d9aa7d5dba87fcfc2b1fdc2c75cab73b891097fbb7f8b371c7656cd07"

        def install
          bin.install "atun"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AutomationD/atun/releases/download/v0.7.1/atun-linux-arm64.tar.gz"
        sha256 "4a16f0937307c684ee8f71b5f60770d81c90d0413e33a0b411fb6d09bb8378a8"

        def install
          bin.install "atun"
        end
      end
    end
  end

  conflicts_with "atun-dev"
  conflicts_with "atun-dev@0.7.1"

  test do
    system "#{bin}/atun version"
  end
end
