# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtunDevAT031 < Formula
  desc "atun.io is a simple SSM/SSH tunnel manager"
  homepage "https://github.com/AutomationD/atun"
  version "0.3.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AutomationD/atun/releases/download/0.3.1/atun_0.3.1_darwin_amd64.tar.gz"
      sha256 "c447a1c4a4bc33ddc906889a7061e4e9611085bf5479981798b9522bfd90855d"

      def install
        bin.install "atun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AutomationD/atun/releases/download/0.3.1/atun_0.3.1_darwin_arm64.tar.gz"
      sha256 "7dc89ab8b84ee0172864cbdf4bc80c59aa60cc4c8751fed9788eef1b935436c5"

      def install
        bin.install "atun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AutomationD/atun/releases/download/0.3.1/atun_0.3.1_linux_amd64.tar.gz"
        sha256 "07a1d0c6d203e2a6d33251444417332ec6c695bf5322a01d029a4344656cbb11"

        def install
          bin.install "atun"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AutomationD/atun/releases/download/0.3.1/atun_0.3.1_linux_arm64.tar.gz"
        sha256 "70184b4a1f6f5f1e5931dc155fa59a56e3aac8e130f1368a0ce1d611479a8ea8"

        def install
          bin.install "atun"
        end
      end
    end
  end

  test do
    system "#{bin}/atun --version"
  end
end
