# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtunAT042 < Formula
  desc "atun.io is a simple SSM/SSH tunnel manager"
  homepage "https://github.com/AutomationD/atun"
  version "0.4.2"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AutomationD/atun/releases/download/0.4.2/atun_0.4.2_darwin_amd64.tar.gz"
      sha256 "ee027c0311c2a59332b5eb3b9d4306a54154bf9963e547b5bff8796a5e4a20c9"

      def install
        bin.install "atun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AutomationD/atun/releases/download/0.4.2/atun_0.4.2_darwin_arm64.tar.gz"
      sha256 "af85b2d69e51c913c8cc3b99f7691ceb719f5cd9b262182a9271d0a17c0540f0"

      def install
        bin.install "atun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AutomationD/atun/releases/download/0.4.2/atun_0.4.2_linux_amd64.tar.gz"
        sha256 "441074a9a095c6f6973ae49b571fbb9c271dea4b616f1867d958f9b075f2073e"

        def install
          bin.install "atun"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AutomationD/atun/releases/download/0.4.2/atun_0.4.2_linux_arm64.tar.gz"
        sha256 "7c369d3964a58d34054322e79f139b5b6438333a75817ec7692b0e669e551c5d"

        def install
          bin.install "atun"
        end
      end
    end
  end

  conflicts_with "atun-dev"
  conflicts_with "atun-dev@0.4.2"

  test do
    system "#{bin}/atun --version"
  end
end
