# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atun < Formula
  desc "atun.io is a simple SSM/SSH tunnel manager"
  homepage "https://github.com/AutomationD/atun"
  version "0.3.2"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AutomationD/atun/releases/download/0.3.2/atun_0.3.2_darwin_amd64.tar.gz"
      sha256 "8008c3e0feb4731b7a61c5a4dd3d5ce5438807ff8b5d425f00b39f35af8f51b2"

      def install
        bin.install "atun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AutomationD/atun/releases/download/0.3.2/atun_0.3.2_darwin_arm64.tar.gz"
      sha256 "da7b230ac47be70a6de42dfe2418e942a32a1341b0b3fecdc6afdbed3a0e724f"

      def install
        bin.install "atun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AutomationD/atun/releases/download/0.3.2/atun_0.3.2_linux_amd64.tar.gz"
        sha256 "401646af197c7bc753178fea45bd322f893a6d87bbcf79c6c1df7b49bd17fbc3"

        def install
          bin.install "atun"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AutomationD/atun/releases/download/0.3.2/atun_0.3.2_linux_arm64.tar.gz"
        sha256 "965ca89b14da89c56499dcab8b1a390146fe6602d218f2d5f30959c2b25c283e"

        def install
          bin.install "atun"
        end
      end
    end
  end

  conflicts_with "atun-dev"
  conflicts_with "atun-dev@0.3.2"

  test do
    system "#{bin}/atun --version"
  end
end
