# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atun < Formula
  desc "atun.io is a simple SSM/SSH tunnel manager"
  homepage "https://github.com/DimmKirr/atun"
  version "0.8.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DimmKirr/atun/releases/download/v0.8.1/atun-darwin-amd64.tar.gz"
      sha256 "59e7ad6e38694ea83404a32073193866e59c274c33afff6a3b9f7d93f6aca09e"

      def install
        bin.install "atun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DimmKirr/atun/releases/download/v0.8.1/atun-darwin-arm64.tar.gz"
      sha256 "f2652b41b44950660eb4d8891b03aaf9a99d61dd7828f31fd494ad9facbbaedf"

      def install
        bin.install "atun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/DimmKirr/atun/releases/download/v0.8.1/atun-linux-amd64.tar.gz"
      sha256 "aca541d6333f581848f808eeb88c5b060afc92018a245810b6cc054896159e6b"
      def install
        bin.install "atun"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/DimmKirr/atun/releases/download/v0.8.1/atun-linux-arm64.tar.gz"
      sha256 "f459359305461775556381e33a64883aafb6af8a5d661b4e09a26a36c69158a7"
      def install
        bin.install "atun"
      end
    end
  end

  conflicts_with "atun-dev"

  test do
    system "#{bin}/atun version"
  end
end
