# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtunDevAT020 < Formula
  desc "atun.io is a simple SSM/SSH tunnel manager"
  homepage "https://github.com/AutomationD/atun"
  version "0.2.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AutomationD/atun/releases/download/0.2.0/atun_0.2.0_darwin_amd64.tar.gz"
      sha256 "a8eadee61d751dd1a07c442c7a3b099db2141562b1eaafc58d4fd52b1ef1357b"

      def install
        bin.install "atun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AutomationD/atun/releases/download/0.2.0/atun_0.2.0_darwin_arm64.tar.gz"
      sha256 "1a7d9daeae3c05844e63eb4e62aa195fed063d310c3e2f3d5df55c30d2680b49"

      def install
        bin.install "atun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AutomationD/atun/releases/download/0.2.0/atun_0.2.0_linux_amd64.tar.gz"
        sha256 "af53e93a4f79ff58c3a85438d77ab4e5ddce60288eadef380b86ba75ecc5e9be"

        def install
          bin.install "atun"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AutomationD/atun/releases/download/0.2.0/atun_0.2.0_linux_arm64.tar.gz"
        sha256 "b946f4b3646145f0f68598b813a20bfdcaccc06c52bd8f0d97ba2382a7a0ed69"

        def install
          bin.install "atun"
        end
      end
    end
  end

  test do
    system "#{bin}/atun --version"
  end
end
