# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AtunDevAT030 < Formula
  desc "atun.io is a simple SSM/SSH tunnel manager"
  homepage "https://github.com/AutomationD/atun"
  version "0.3.0"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AutomationD/atun/releases/download/0.3.0/atun_0.3.0_darwin_amd64.tar.gz"
      sha256 "faa83623dcf05bebad1cdfa88d4d1a69dba54dac86ca070d7fd405565b46f728"

      def install
        bin.install "atun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AutomationD/atun/releases/download/0.3.0/atun_0.3.0_darwin_arm64.tar.gz"
      sha256 "c10bd8b3b14d14dfe09511f58b957b992998752df753608b6c7a5f6334f67a2c"

      def install
        bin.install "atun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AutomationD/atun/releases/download/0.3.0/atun_0.3.0_linux_amd64.tar.gz"
        sha256 "811a79cf85339f5a1ad035328c5bc53846076a2ae5e50dedac4e6dffa2300453"

        def install
          bin.install "atun"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/AutomationD/atun/releases/download/0.3.0/atun_0.3.0_linux_arm64.tar.gz"
        sha256 "ab725c06ddbd86a445ef48a4c93ffdde1c70990d7fbf0903855eea1ad5b0486a"

        def install
          bin.install "atun"
        end
      end
    end
  end

  test do
    system "#{bin}/atun --version"
  end
end
